# Generated by Django 5.0 on 2024-01-03 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalbankapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('Savings', 'Savings Account'), ('Checking', 'Current Account'), ('Student', 'Student Account'), ('Business', 'Business Account'), ('Loan', 'Loan Account')], max_length=40)),
                ('phon', models.BigIntegerField()),
                ('photo', models.FileField(upload_to='image/')),
                ('adhar', models.FileField(upload_to='adhar/')),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('account_number', models.BigIntegerField(unique=True)),
                ('interest_rate', models.IntegerField(blank=True, null=True)),
                ('Users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
