# Generated by Django 5.0 on 2024-01-03 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalbankapp', '0002_bankusers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creaditcard', models.BooleanField(blank=True, default=False, null=True)),
                ('debitcard', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Loan_Tenure', models.IntegerField(default=1)),
                ('purpose', models.CharField(choices=[('home', 'Home Purchase'), ('Helth', 'Helth Loan'), ('car', 'Car Loan'), ('education', 'Education'), ('personal', 'Personal'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Credited', models.DecimalField(decimal_places=4, max_digits=16)),
                ('Debited', models.DecimalField(decimal_places=4, max_digits=16)),
                ('Transferred', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emi', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('bank_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royalbankapp.bankusers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
