# Generated by Django 5.0 on 2024-01-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalbankapp', '0003_cardapplication_loanrequest_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankusers',
            name='current_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bankusers',
            name='loan_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
