# Generated by Django 5.0 on 2024-01-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalbankapp', '0004_alter_bankusers_current_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Credited',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Debited',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Transferred',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='emi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
