# Generated by Django 5.0 on 2024-01-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalbankapp', '0005_alter_transaction_credited_alter_transaction_debited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankusers',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='emi',
        ),
        migrations.AddField(
            model_name='bankusers',
            name='emi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
