# Generated by Django 5.0 on 2024-01-14 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royalbankapp', '0006_remove_bankusers_interest_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='timestamp',
            new_name='Timedata',
        ),
    ]
