# Generated by Django 5.0 on 2024-01-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalbankapp', '0008_alter_transaction_timedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_field',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='time_field',
            field=models.TimeField(auto_now=True),
        ),
    ]
