# Generated by Django 5.0 on 2024-01-14 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royalbankapp', '0009_transaction_date_field_transaction_time_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Timedata',
        ),
    ]
